multithreaded aggregation
cs-23-sw-7-06/CentralHub pull request #44
Opened 2023-12-04 13:05 UTC by Casper-NS

2023-12-04 13:28 UTC, mads256h approved these changes

2023-12-04 13:41 UTC, Taoshix approved these changes
Multithreadding and async at the same time??? never throught I would get to see it

2023-12-04 13:46 UTC, Mast3rwaf1z requested changes

2023-12-04 14:37 UTC, Mast3rwaf1z approved these changes
nice, no more comments then

2023-12-05 08:08 UTC, mads256h approved these changes

2023-12-05 08:21 UTC, merged