removed all template files etc.
cs-23-sw-7-06/CentralHub pull request #6
Opened 2023-11-03 09:36 UTC by miniJmo

2023-11-03 12:18 UTC, miniJmo commented
so... I added a little more than first intended

2023-11-03 12:50 UTC, Taoshix approved these changes
こんいちは、Miniさん、それらの変化はとても面白いね。頑張れ！

2023-11-04 13:25 UTC, mads256h requested changes

2023-11-04 13:25 UTC, mads256h commented on CentralHub.WebUI/Pages/Trackers.razor
> +            <th> Location</th>
```suggestion
            <th>Location</th>
```

2023-11-04 13:25 UTC, mads256h commented on CentralHub.Api.Model/Tracker.cs
> +        Location = location;
We should probably add a Room class

2023-11-06 08:05 UTC, miniJmo commented on CentralHub.Api.Model/Tracker.cs
> +        Location = location;
yeah det er nok en god ide

2023-11-06 08:09 UTC, mads256h approved these changes

2023-11-06 08:09 UTC, merged